version: "3.9"

services:
  fastchat-controller:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ghcr.io/intelligent-systems-lab/fastchat:latest
    ports:
      - "21001:21001"
    entrypoint: ["python3.9", "-m", "fastchat.serve.controller", "--host", "0.0.0.0", "--port", "21001"]
  fastchat-api-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ghcr.io/intelligent-systems-lab/fastchat:latest
    ports:
      - "8000:8000"
    entrypoint: ["python3.9", "-m", "fastchat.serve.openai_api_server", "--controller-address", "http://fastchat-controller:21001", "--host", "0.0.0.0", "--port", "8000"]
  fastchat-web-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ghcr.io/intelligent-systems-lab/fastchat:latest
    ports:
      - "7860:7860"
    entrypoint: ["python3.9", "-m", "fastchat.serve.gradio_web_server_multi", "--controller-url", "http://fastchat-controller:21001", "--model-list-mode", "reload"]
volumes:
  huggingface:
